version: 2
updates:
  - package-ecosystem: maven
    registries:
      - nexus-releases
    directory: '/'
    schedule:
      interval: weekly
    groups:
      java:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    groups:
      pipeline:
        patterns:
          - "*"
